disabled_rules:
  - trailing_whitespace
  - orphaned_doc_comment
  - inclusive_language
  - class_delegate_protocol
  - large_tuple

identifier_name:
  excluded:
    - id
    - to

cyclomatic_complexity:
  ignores_case_statements: true

line_length:
  - 192 # warning
  - 256 # error

nesting:
  type_level:
    warning: 4
    error: 6


opt_in_rules:
    - array_init
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - conditional_returns_on_newline
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - contains_over_range_nil_comparison
    - discarded_notification_center_observer
    - discouraged_object_literal
    - discouraged_optional_boolean
    - discouraged_optional_collection
    - empty_collection_literal
    - empty_count
    - empty_string
    - empty_xctest_method
    - enum_case_associated_values_count
    - explicit_init
    - fallthrough
    - fatal_error_message
    - first_where
    - flatmap_over_map_reduce
    - for_where
    - identical_operands
    - implicit_return
    - joined_default_parameter
    - last_where
    - legacy_multiple
    - legacy_random
    - literal_expression_end_indentation
    - lower_acl_than_parent
    - modifier_order
    - multiline_arguments
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - multiline_parameters_brackets
    - nimble_operator
    - operator_usage_whitespace
    - overridden_super_call
    - prefer_self_type_over_type_of_self
    - prefer_zero_over_explicit_init
    - private_action
    - private_outlet
    - prohibited_super_call
    - redundant_nil_coalescing
    - redundant_type_annotation
    - required_enum_case
    - sorted_first_last
    - static_operator
    - strong_iboutlet
    - switch_case_on_newline
    - test_case_accessibility
    - toggle_bool
    - unavailable_function
    - unneeded_parentheses_in_closure_argument
    - unowned_variable_capture
    - untyped_error_in_catch
    - vertical_whitespace_closing_braces
    - vertical_whitespace_opening_braces
    - yoda_condition

identifier_name:
    max_length:
        warning: 96
        error: 96
    min_length:
        warning: 2
        error: 2
    excluded:
        - 'id'

function_body_length:
  warning: 60
  error: 80

type_name:
    max_length:
        warning: 96
        error: 96
    min_length:
        warning: 4
        error: 4
    excluded:
        - 'Tab'

line_length:
  - 192 # warning
  - 256 # error
